Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: evaluate in /mnt/irisgpfs/users/gmenon/.local/lib/python3.8/site-packages (0.4.0)
Requirement already satisfied: datasets>=2.0.0 in /mnt/irisgpfs/users/gmenon/.local/lib/python3.8/site-packages (from evaluate) (2.13.2.dev1)
Requirement already satisfied: numpy>=1.17 in /mnt/irisgpfs/users/gmenon/.local/lib/python3.8/site-packages (from evaluate) (1.23.5)
Requirement already satisfied: dill in /mnt/irisgpfs/users/gmenon/.local/lib/python3.8/site-packages (from evaluate) (0.3.6)
Requirement already satisfied: pandas in /mnt/irisgpfs/users/gmenon/.local/lib/python3.8/site-packages (from evaluate) (1.5.3)
Requirement already satisfied: requests>=2.19.0 in /mnt/irisgpfs/users/gmenon/.local/lib/python3.8/site-packages (from evaluate) (2.28.2)
Requirement already satisfied: tqdm>=4.62.1 in /mnt/irisgpfs/users/gmenon/.local/lib/python3.8/site-packages (from evaluate) (4.65.0)
Requirement already satisfied: xxhash in /mnt/irisgpfs/users/gmenon/.local/lib/python3.8/site-packages (from evaluate) (3.2.0)
Requirement already satisfied: multiprocess in /mnt/irisgpfs/users/gmenon/.local/lib/python3.8/site-packages (from evaluate) (0.70.14)
Requirement already satisfied: fsspec[http]>=2021.05.0 in /mnt/irisgpfs/users/gmenon/.local/lib/python3.8/site-packages (from evaluate) (2023.6.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /mnt/irisgpfs/users/gmenon/.local/lib/python3.8/site-packages (from evaluate) (0.16.4)
Requirement already satisfied: packaging in /mnt/irisgpfs/users/gmenon/.local/lib/python3.8/site-packages (from evaluate) (23.1)
Requirement already satisfied: responses<0.19 in /mnt/irisgpfs/users/gmenon/.local/lib/python3.8/site-packages (from evaluate) (0.18.0)
Requirement already satisfied: pyarrow>=8.0.0 in /mnt/irisgpfs/users/gmenon/.local/lib/python3.8/site-packages (from datasets>=2.0.0->evaluate) (12.0.1)
Requirement already satisfied: aiohttp in /mnt/irisgpfs/users/gmenon/.local/lib/python3.8/site-packages (from datasets>=2.0.0->evaluate) (3.8.4)
Requirement already satisfied: pyyaml>=5.1 in /mnt/irisgpfs/users/gmenon/.local/lib/python3.8/site-packages (from datasets>=2.0.0->evaluate) (6.0)
Requirement already satisfied: filelock in /mnt/irisgpfs/apps/resif/iris-rhel8/2020b/gpu/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages (from huggingface-hub>=0.7.0->evaluate) (3.0.12)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /mnt/irisgpfs/users/gmenon/.local/lib/python3.8/site-packages (from huggingface-hub>=0.7.0->evaluate) (4.7.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /mnt/irisgpfs/users/gmenon/.local/lib/python3.8/site-packages (from requests>=2.19.0->evaluate) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /mnt/irisgpfs/apps/resif/iris-rhel8/2020b/gpu/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages (from requests>=2.19.0->evaluate) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /mnt/irisgpfs/apps/resif/iris-rhel8/2020b/gpu/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages (from requests>=2.19.0->evaluate) (1.25.10)
Requirement already satisfied: certifi>=2017.4.17 in /mnt/irisgpfs/apps/resif/iris-rhel8/2020b/gpu/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages (from requests>=2.19.0->evaluate) (2020.6.20)
Requirement already satisfied: python-dateutil>=2.8.1 in /mnt/irisgpfs/users/gmenon/.local/lib/python3.8/site-packages (from pandas->evaluate) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /mnt/irisgpfs/apps/resif/iris-rhel8/2020b/gpu/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages (from pandas->evaluate) (2020.1)
Requirement already satisfied: attrs>=17.3.0 in /mnt/irisgpfs/apps/resif/iris-rhel8/2020b/gpu/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (20.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /mnt/irisgpfs/users/gmenon/.local/lib/python3.8/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /mnt/irisgpfs/users/gmenon/.local/lib/python3.8/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /mnt/irisgpfs/users/gmenon/.local/lib/python3.8/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /mnt/irisgpfs/users/gmenon/.local/lib/python3.8/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in /mnt/irisgpfs/users/gmenon/.local/lib/python3.8/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.1)
Requirement already satisfied: six>=1.5 in /mnt/irisgpfs/apps/resif/iris-rhel8/2020b/gpu/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages (from python-dateutil>=2.8.1->pandas->evaluate) (1.15.0)
